name: Terraform Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2.0.0
        with:
          terraform_version: 1.4.5

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-south-1"

      - name: Check Policy with OPA
        run: |
          wget https://github.com/open-policy-agent/opa/releases/latest/download/opa_linux_amd64 -O opa
          chmod +x opa
          opa eval --input tfplan --data policy.rego "data.s3_bucket.allow"
