name: Validate S3 Bucket Tags

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  check-policy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install OPA
        run: |
          wget https://github.com/open-policy-agent/opa/releases/latest/download/opa_linux_amd64 -O opa
          chmod +x opa
          sudo mv opa /usr/local/bin/

      - name: Prepare Input Data
        run: |
          echo '{
            "resource_type": "s3_bucket",
            "action": "create",
            "tags": {
              "Environment": "Production",
              "Owner": "TeamA"
            }
          }' > input.json

      - name: Validate Policy
        run: |
          opa eval --data policies/s3_tag_policy.rego --input input.json "data.example.s3.allow" || exit 1

      - name: Policy Check Passed
        if: success()  # This will run only if the previous step succeeded
        run: echo "Policy check passed!"
